# Copyright the Hyperledger Fabric contributors. All rights reserved.
#
# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
  batch: false
  branches:
    include:
    - master
    - release-*

variables:
  branch: $[ coalesce(variables['system.PullRequest.TargetBranch'], variables['build.SourceBranchName']) ]

pool:
  vmImage: ubuntu-16.04
container:
  image: golang:1.12.9-buster

steps:
- checkout: self
  clean: true
  fetchDepth: 1

- script: |
    set -eu -o pipefail
    go test -race ./...
